module DHT11(
	sys_clk,
	rst_n,
	data_r,
	himi  ,
	temp);

	//---Ports declearation: generated by Robei---
	input sys_clk;
	input rst_n;
	inout data_r;
	output [7:0] himi  ;
	output [7:0] temp;

	wire sys_clk;
	wire rst_n;
	wire data_r;
	reg [7:0] himi  ;
	reg [7:0] temp;

	//----Code starts here: integrated by Robei-----
	reg    [3:0]       state_d  ; //状态机寄存器
	reg    [27:0]     cnt_1s = 0;   
	reg    [11:0]      cnt_40us = 0;
	reg    [19:0]     cnt_18ms = 0;
	reg    [7:0]       num;
	reg    [3:0]       state = 0;
	reg                  data_redy;
	//reg    [7:0]      himi; //湿度
	//reg    [7:0]      temp;//温度
	reg    [39:0]    get_data;
	reg                  datar;
	
	wire            data_up;
	
	assign    data_up =  datar;
	assign    data_r = datar;
	
	always @(posedge sys_clk)
	begin
		case(state_d)
		0: begin
				datar<=1;//初始为1
				cnt_1s<=cnt_1s+1;
				if(cnt_1s[26]==1)
					begin
						cnt_1s<=0;
						state<=1;
					end
			end
		1: begin
				datar<=0;
				//if(pulse==1) //使能启动转换
					//begin
						cnt_18ms<=0;
						datar<=0; //总线为0
						state<=2;
					//end
			end
		2: begin
				cnt_18ms<=cnt_18ms+1;
				if(cnt_18ms[20]==1) //使能启动转换
					begin
						cnt_18ms<=0;
						cnt_40us<=0;
						datar<=1; //总线为1
						state<=3;
					end
			end
		3: begin
				cnt_40us<=cnt_40us+1;
				if(cnt_40us[11]==1) 
					begin
						cnt_40us<=0;
						state<=4;
					end
			end
		
		4: begin
				if(data_up==1)
					begin
						get_data<=40'd0;
						num<=0;
						state<=5;
					end
			end
		5:begin
				if(data_up==1)
				begin
					cnt_40us<=0;
					state<=6;
				end
			end
		6:begin
			cnt_40us<=cnt_40us+1;
			if(cnt_40us[11]==1)
				begin
					cnt_40us<=0;
					num<=num+1;
				if(data_r)
					get_data<={get_data[38:0],1'b1}; //串行
				else
					get_data<={get_data[38:0],1'b0};
				if(num==39)
					begin
						num<=0;
						data_redy<=1;
						state<=1;
					end
				else
						state<=5;
				end
			end
		default:  state <= 0;   
	   endcase         
	end 
	
	always@(posedge sys_clk or posedge rst_n) begin
	    if(!rst_n) begin
	          himi <= 0;
	          temp <= 0;
	    end
	    else if(num==39) begin 
	         himi = get_data[39:31];
	         temp = get_data[23:15];
	    end
	
	end
	
	
	
	
	
	
endmodule    //DHT11

