module eobei_end_top(
	sys_clk,
	rst_n,
	IRF1,
	IRF2,
	IRF3,
	data,
	pwm1,
	pwm2,
	pwm3,
	tele11,
	tele12,
	tele21,
	tele22,
	tele31,
	tele32,
	yundongp,
	out_pwm1,
	out_pwm2,
	txd,
	IN_illumination,
	IN_error);

	//---Ports declearation: generated by Robei---
	input sys_clk;
	input rst_n;
	input IRF1;
	input IRF2;
	input IRF3;
	inout data;
	output pwm1;
	output pwm2;
	output pwm3;
	output tele11;
	output tele12;
	output tele21;
	output tele22;
	output tele31;
	output tele32;
	output yundongp;
	output out_pwm1;
	output out_pwm2;
	output txd;
	input IN_illumination;
	input IN_error;

	wire sys_clk;
	wire rst_n;
	wire IRF1;
	wire IRF2;
	wire IRF3;
	wire data;
	wire pwm1;
	wire pwm2;
	wire pwm3;
	wire tele11;
	wire tele12;
	wire tele21;
	wire tele22;
	wire tele31;
	wire tele32;
	wire yundongp;
	wire out_pwm1;
	wire out_pwm2;
	wire txd;
	wire IN_illumination;
	wire IN_error;
	wire ml302_loge10_tx_data_valid;
	wire [7:0] ml302_loge10_tx_data_in;
	wire yuliu9_out;
	wire [2:0] slever_m1_en_slever;
	wire [1:0] slever_m1_tele_en1;
	wire [1:0] slever_m1_tele_en2;
	wire [1:0] slever_m1_tele_en3;
	wire slever_m1_pwm_en1;
	wire slever_m1_pwm_en2;
	wire slever_m1_pwm_en3;
	wire worek_u8_out;
	wire worek_u8_out1;
	wire [7:0] DHT1110_himi  ;
	wire [7:0] DHT1110_temp;
	wire sign_made11_IRF_sign;
	wire sign_made212_IRF_sign1;
	wire sign_made313_IRF_sign2;

	//----Code starts here: integrated by Robei-----
	
	
	
	
	//---Module instantiation---
	slever_m slever_m1(
		.sys_clk(sys_clk),
		.IRF_1(sign_made11_IRF_sign),
		.rst_n(rst_n),
		.pwm_en2(slever_m1_pwm_en2),
		.en_slever(slever_m1_en_slever),
		.IRF_3(sign_made313_IRF_sign2),
		.IRF_2(sign_made212_IRF_sign1),
		.tele_en2(slever_m1_tele_en2),
		.pwm_en1(slever_m1_pwm_en1),
		.pwm_en3(slever_m1_pwm_en3),
		.tele_en1(slever_m1_tele_en1),
		.tele_en3(slever_m1_tele_en3));

	uart_send uart_send6(
		.sys_clk(sys_clk),
		.sys_rst_n(rst_n),
		.uart_en(ml302_loge10_tx_data_valid),
		.uart_din(ml302_loge10_tx_data_in),
		.uart_txd(txd));

	ml302_loge ml302_loge10(
		.sys_clk(sys_clk),
		.rst_n(rst_n),
		.IN_tempruter(DHT1110_temp),
		.tx_data_in(ml302_loge10_tx_data_in),
		.tx_data_valid(ml302_loge10_tx_data_valid),
		.IN_wate(DHT1110_himi  ),
		.IN_illumination(IN_illumination),
		.IN_erroe(IN_error),
		.bps_en_tx(yuliu9_out));

	yuliu yuliu9(
		.sys_clk(sys_clk),
		.out(yuliu9_out));

	worek_u worek_u8(
		.sys_clk(sys_clk),
		.out(worek_u8_out),
		.out1(worek_u8_out1),
		.IRF_sing(IRF1),
		.woek_en(slever_m1_en_slever));

	analtsis_tele analtsis_tele7(
		.sys_clk(sys_clk),
		.tele_sign_in1(slever_m1_tele_en1),
		.tele_out11(tele11),
		.tele_out12(tele12),
		.tele_sign_in2(slever_m1_tele_en2),
		.tele_sign_in3(slever_m1_tele_en3),
		.tele_out21(tele21),
		.tele_out22(tele22),
		.tele_out31(tele31),
		.tele_out32(tele32));

	pwm_0_90 pwm_0_908(
		.sys_clk(sys_clk),
		.pwm1(slever_m1_pwm_en1),
		.pwm2(slever_m1_pwm_en2),
		.pwm3(slever_m1_pwm_en3),
		.outp1(pwm1),
		.outp2(pwm2),
		.outp3(pwm3));

	pwm_0_work pwm_0_work9(
		.sys_clk(sys_clk),
		.pwm_in_1(worek_u8_out),
		.pwm_in_2(worek_u8_out1),
		.pwm_out1(out_pwm1),
		.pwm_out2(out_pwm2));

	DHT11 DHT1110(
		.sys_clk(sys_clk),
		.rst_n(rst_n),
		.data_r(data),
		.himi  (DHT1110_himi  ),
		.temp(DHT1110_temp));

	yundong yundong10(
		.sys_clk(sys_clk),
		.rst_n(rst_n),
		.outyd(yundongp),
		.m_en(slever_m1_en_slever));

	sign_made sign_made11(
		.sys_clk(sys_clk),
		.IRF(IRF1),
		.IRF_sign(sign_made11_IRF_sign));

	sign_made2 sign_made212(
		.sys_clk(sys_clk),
		.IRF2(IRF2),
		.IRF_sign1(sign_made212_IRF_sign1));

	sign_made3 sign_made313(
		.sys_clk(sys_clk),
		.IRF3(IRF3),
		.IRF_sign2(sign_made313_IRF_sign2));

endmodule    //eobei_end_top

