module pwm_0_90(
	sys_clk,
	pwm1,
	pwm2,
	pwm3,
	outp1,
	outp2,
	outp3);

	//---Ports declearation: generated by Robei---
	input sys_clk;
	input pwm1;
	input pwm2;
	input pwm3;
	output outp1;
	output outp2;
	output outp3;

	wire sys_clk;
	wire pwm1;
	wire pwm2;
	wire pwm3;
	reg outp1;
	reg outp2;
	reg outp3;

	//----Code starts here: integrated by Robei-----
		parameter      siez2 = 125000; //180D
		parameter      siez1 = 25000;   //1.5ms
		parameter      sizea = 75000;  //90D
	    parameter      size3 = 80000; //2hao
	    parameter      size4 = 150000;
		
		//reg cnt
		reg         [19:0]       pwm_cnt = 0;
		
		
		//时钟计数信号发生always
		always @(posedge sys_clk) begin
		      if(pwm_cnt == 906255) begin
		             pwm_cnt <= 0;
		      end
		      else begin
		             pwm_cnt = pwm_cnt+1;
		      end
		end
		
		//一路pwm生成快
		always@(posedge sys_clk) begin
		     if(pwm1) begin
		        if(pwm_cnt < siez1) begin
		               outp1 <= 1;
		        end
		        else begin
		               outp1 <= 0;
		        end
		     end
		     else begin
		          if(pwm_cnt < sizea) begin
		               outp1 <= 1;
		        end
		        else begin
		               outp1 <= 0;
		        end
		     end
		end 
		
		//二路pwm生成快
		always@(posedge sys_clk) begin
		     if(pwm2) begin
		        if(pwm_cnt < siez2) begin 
		               outp2 <= 1;
		        end
		        else begin
		               outp2 <= 0;
		        end
		     end
		     else begin
		          if(pwm_cnt < sizea) begin
		               outp2 <= 1;
		        end
		        else begin
		               outp2 <= 0;
		        end
		     end
		end
		
		//三路pwm生成快
		always@(posedge sys_clk ) begin
		     if(pwm3) begin
		        if(pwm_cnt < siez1) begin
		               outp3 <= 1;
		        end
		        else begin
		               outp3 <= 0;
		        end
		     end
		     else begin
		          if(pwm_cnt < sizea) begin
		               outp3 <= 1;
		        end
		        else begin
		               outp3 <= 0;
		        end
		     end
		end
endmodule    //pwm_0_90

