module sign_made3(
	sys_clk,
	IRF3,
	IRF_sign2);

	//---Ports declearation: generated by Robei---
	input sys_clk;
	input IRF3;
	output IRF_sign2;

	wire sys_clk;
	wire IRF3;
	reg IRF_sign2;

	//----Code starts here: integrated by Robei-----
	//parameter       MADE12 = 800000000;
	parameter       MADEFZ2 = 800000000;
	
	reg         [31:0]      made_cnt2 = 0;
	
	reg                         IRF_m_sign2;
	
	always@(posedge sys_clk) begin
	         if(IRF_m_sign2) begin
	                  if(made_cnt2 < MADEFZ2) begin
	                         IRF_sign2 <= 1;
	                        made_cnt2 = made_cnt2 + 1; 
	                  end
	                  else begin
	                        made_cnt2 = made_cnt2 + 1; 
	                  end
	         end
	        else begin
	                  made_cnt2 <= 0;
	                  IRF_sign2 <= 0;
	        end
	
	end
	
	always@(posedge sys_clk) begin
	        if(!IRF3) begin
	             IRF_m_sign2 <= 1;
	        end
	        else if(made_cnt2 == MADEFZ2) begin
	             IRF_m_sign2 <= 0;
	        end
	        else begin
	             IRF_m_sign2 <= IRF_m_sign2;
	        end
	
	end
	
	
	
	
endmodule    //sign_made3

