module sign_made2(
	sys_clk,
	IRF2,
	IRF_sign1);

	//---Ports declearation: generated by Robei---
	input sys_clk;
	input IRF2;
	output IRF_sign1;

	wire sys_clk;
	wire IRF2;
	reg IRF_sign1;

	//----Code starts here: integrated by Robei-----
	//parameter       MADE11 = 800000000;
	parameter       MADEFZ1 = 800000000;
	
	reg         [31:0]      made_cnt1 = 0;
	
	reg                         IRF_m_sign1;
	
	always@(posedge sys_clk) begin
	         if(IRF_m_sign1) begin
	                  if(made_cnt1 < MADEFZ1) begin
	                         IRF_sign1 <= 1;
	                        made_cnt1 = made_cnt1 + 1; 
	                  end
	                  else begin
	                        made_cnt1 = made_cnt1 + 1; 
	                  end
	         end
	        else begin
	                  made_cnt1 <= 0;
	                  IRF_sign1 <= 0;
	        end
	
	end
	
	always@(posedge sys_clk) begin
	        if(!IRF2) begin
	             IRF_m_sign1 <= 1;
	        end
	        else if(made_cnt1 == MADEFZ1) begin
	             IRF_m_sign1 <= 0;
	        end
	        else begin
	             IRF_m_sign1 <= IRF_m_sign1;
	        end
	
	end
	
	
	
endmodule    //sign_made2

