module yuliu(
	sys_clk,
	out);

	//---Ports declearation: generated by Robei---
	input sys_clk;
	output out;

	wire sys_clk;
	reg out;

	//----Code starts here: integrated by Robei-----
	//预留口的信号发生块
	always@(posedge sys_clk) begin
	        out <= 1;
	end
	
	
	
endmodule    //yuliu

