module yundong(
	sys_clk,
	rst_n,
	outyd,
	m_en);

	//---Ports declearation: generated by Robei---
	input sys_clk;
	input rst_n;
	output outyd;
	input [2:0] m_en;

	wire sys_clk;
	wire rst_n;
	reg outyd;
	wire [2:0] m_en;

	//----Code starts here: integrated by Robei-----
	//reg cnt define
	
	
	//ÔË¶¯Ä£¿é
	always@(posedge sys_clk or posedge rst_n) begin
	
	      if(!rst_n) begin
	           outyd <= 0;
	      end
	      else begin
	            if(!m_en) begin
	                outyd <= 1;
	            end
	            else begin
	                outyd <= 0;
	            end
	            
	      end
	
	end
	
	
	
endmodule    //yundong

